import equal from 'fast-deep-equal';
import { toString } from '../../../src/utils/String';
import { ContextAnalysisResult } from '../../utils/TemplateTestOrchestrator';

export function verify(expected: ContextAnalysisResult, actual: ContextAnalysisResult) {
    if (!equal(expected, actual)) {
        console.log('Expected', toString(expected)); // eslint-disable-line no-console
        console.log('Actual', toString(actual)); // eslint-disable-line no-console
        throw new Error('ContextAnalysis results are different');
    }
}

export const EXPECTED: Record<
    string,
    Record<'json' | 'yaml', Record<string, Record<string, ContextAnalysisResult>>>
> = {
    comprehensive: {
        json: {
            Metadata: {
                'AWS::CloudFormation::Interface': {
                    section: 'Metadata',
                    logicalId: 'AWS::CloudFormation::Interface',
                    numPositions: 247,
                    valid: 246,
                    numVerifiedPositions: 247,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[10, 0]],
                },
                CustomMetadata: {
                    section: 'Metadata',
                    logicalId: 'CustomMetadata',
                    numPositions: 157,
                    valid: 156,
                    numVerifiedPositions: 157,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[28, 0]],
                },
            },
            Parameters: {
                EnvironmentName: {
                    section: 'Parameters',
                    logicalId: 'EnvironmentName',
                    numPositions: 181,
                    valid: 178,
                    numVerifiedPositions: 181,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [43, 0],
                        [52, 5],
                        [52, 6],
                    ],
                },
                VpcCidr: {
                    section: 'Parameters',
                    logicalId: 'VpcCidr',
                    numPositions: 210,
                    valid: 207,
                    numVerifiedPositions: 210,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [53, 0],
                        [57, 5],
                        [57, 6],
                    ],
                },
                SubnetCidrs: {
                    section: 'Parameters',
                    logicalId: 'SubnetCidrs',
                    numPositions: 85,
                    valid: 83,
                    numVerifiedPositions: 85,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [58, 0],
                        [58, 18],
                    ],
                },
                DatabasePassword: {
                    section: 'Parameters',
                    logicalId: 'DatabasePassword',
                    numPositions: 96,
                    valid: 94,
                    numVerifiedPositions: 96,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [62, 0],
                        [62, 23],
                    ],
                },
                InstanceCount: {
                    section: 'Parameters',
                    logicalId: 'InstanceCount',
                    numPositions: 89,
                    valid: 87,
                    numVerifiedPositions: 89,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [68, 0],
                        [68, 20],
                    ],
                },
                AvailabilityZones: {
                    section: 'Parameters',
                    logicalId: 'AvailabilityZones',
                    numPositions: 97,
                    valid: 95,
                    numVerifiedPositions: 97,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [74, 0],
                        [74, 24],
                    ],
                },
                SSMParameter: {
                    section: 'Parameters',
                    logicalId: 'SSMParameter',
                    numPositions: 97,
                    valid: 95,
                    numVerifiedPositions: 97,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [78, 0],
                        [78, 19],
                    ],
                },
                BooleanParameter: {
                    section: 'Parameters',
                    logicalId: 'BooleanParameter',
                    numPositions: 107,
                    valid: 105,
                    numVerifiedPositions: 107,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [82, 0],
                        [82, 23],
                    ],
                },
            },
            Mappings: {
                RegionMap: {
                    section: 'Mappings',
                    logicalId: 'RegionMap',
                    numPositions: 168,
                    valid: 165,
                    numVerifiedPositions: 168,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [93, 0],
                        [102, 5],
                        [102, 6],
                    ],
                },
                EnvironmentMap: {
                    section: 'Mappings',
                    logicalId: 'EnvironmentMap',
                    numPositions: 160,
                    valid: 158,
                    numVerifiedPositions: 160,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [103, 0],
                        [112, 5],
                    ],
                },
            },
            Conditions: {
                IsProduction: {
                    section: 'Conditions',
                    logicalId: 'IsProduction',
                    numPositions: 87,
                    valid: 85,
                    numVerifiedPositions: 87,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [116, 0],
                        [116, 19],
                    ],
                },
                IsNotProduction: {
                    section: 'Conditions',
                    logicalId: 'IsNotProduction',
                    numPositions: 74,
                    valid: 72,
                    numVerifiedPositions: 74,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [124, 0],
                        [124, 22],
                    ],
                },
                IsDevelopment: {
                    section: 'Conditions',
                    logicalId: 'IsDevelopment',
                    numPositions: 87,
                    valid: 85,
                    numVerifiedPositions: 87,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [131, 0],
                        [131, 20],
                    ],
                },
                IsProductionOrStaging: {
                    section: 'Conditions',
                    logicalId: 'IsProductionOrStaging',
                    numPositions: 174,
                    valid: 171,
                    numVerifiedPositions: 174,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [139, 0],
                        [153, 5],
                        [153, 6],
                    ],
                },
                ComplexCondition: {
                    section: 'Conditions',
                    logicalId: 'ComplexCondition',
                    numPositions: 262,
                    valid: 259,
                    numVerifiedPositions: 262,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [154, 0],
                        [175, 5],
                        [175, 6],
                    ],
                },
                HasMultipleAZs: {
                    section: 'Conditions',
                    logicalId: 'HasMultipleAZs',
                    numPositions: 202,
                    valid: 200,
                    numVerifiedPositions: 202,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [176, 0],
                        [192, 5],
                    ],
                },
            },
            Rules: {
                ValidateRegionAndEnvironment: {
                    section: 'Rules',
                    logicalId: 'ValidateRegionAndEnvironment',
                    numPositions: 968,
                    valid: 965,
                    numVerifiedPositions: 968,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [196, 0],
                        [259, 5],
                        [259, 6],
                    ],
                },
                ValidateParameterCombinations: {
                    section: 'Rules',
                    logicalId: 'ValidateParameterCombinations',
                    numPositions: 1615,
                    valid: 1613,
                    numVerifiedPositions: 1615,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [260, 0],
                        [354, 5],
                    ],
                },
            },
            Resources: {
                VPC: {
                    section: 'Resources',
                    logicalId: 'VPC',
                    numPositions: 429,
                    valid: 428,
                    numVerifiedPositions: 429,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[358, 0]],
                },
                PublicSubnet: {
                    section: 'Resources',
                    logicalId: 'PublicSubnet',
                    numPositions: 797,
                    valid: 796,
                    numVerifiedPositions: 797,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[386, 0]],
                },
                WebSecurityGroup: {
                    section: 'Resources',
                    logicalId: 'WebSecurityGroup',
                    numPositions: 843,
                    valid: 842,
                    numVerifiedPositions: 843,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[439, 0]],
                },
                BastionSecurityGroup: {
                    section: 'Resources',
                    logicalId: 'BastionSecurityGroup',
                    numPositions: 282,
                    valid: 281,
                    numVerifiedPositions: 282,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[487, 0]],
                },
                LaunchTemplate: {
                    section: 'Resources',
                    logicalId: 'LaunchTemplate',
                    numPositions: 917,
                    valid: 916,
                    numVerifiedPositions: 917,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[504, 0]],
                },
                AutoScalingGroup: {
                    section: 'Resources',
                    logicalId: 'AutoScalingGroup',
                    numPositions: 1097,
                    valid: 1096,
                    numVerifiedPositions: 1097,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[561, 0]],
                },
                Database: {
                    section: 'Resources',
                    logicalId: 'Database',
                    numPositions: 1199,
                    valid: 1198,
                    numVerifiedPositions: 1199,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[630, 0]],
                },
                DatabaseSecurityGroup: {
                    section: 'Resources',
                    logicalId: 'DatabaseSecurityGroup',
                    numPositions: 320,
                    valid: 319,
                    numVerifiedPositions: 320,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[712, 0]],
                },
                LambdaFunction: {
                    section: 'Resources',
                    logicalId: 'LambdaFunction',
                    numPositions: 1243,
                    valid: 1242,
                    numVerifiedPositions: 1243,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[731, 0]],
                },
                LambdaRole: {
                    section: 'Resources',
                    logicalId: 'LambdaRole',
                    numPositions: 864,
                    valid: 863,
                    numVerifiedPositions: 864,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[798, 0]],
                },
                DatabaseAlarm: {
                    section: 'Resources',
                    logicalId: 'DatabaseAlarm',
                    numPositions: 561,
                    valid: 560,
                    numVerifiedPositions: 561,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[842, 0]],
                },
                SNSTopic: {
                    section: 'Resources',
                    logicalId: 'SNSTopic',
                    numPositions: 428,
                    valid: 427,
                    numVerifiedPositions: 428,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[873, 0]],
                },
            },
            Outputs: {
                VPCId: {
                    section: 'Outputs',
                    logicalId: 'VPCId',
                    numPositions: 156,
                    valid: 155,
                    numVerifiedPositions: 156,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[902, 0]],
                },
                VPCCidr: {
                    section: 'Outputs',
                    logicalId: 'VPCCidr',
                    numPositions: 195,
                    valid: 192,
                    numVerifiedPositions: 195,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [913, 0],
                        [926, 5],
                        [926, 6],
                    ],
                },
                DatabaseEndpoint: {
                    section: 'Outputs',
                    logicalId: 'DatabaseEndpoint',
                    numPositions: 236,
                    valid: 233,
                    numVerifiedPositions: 236,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [927, 0],
                        [941, 5],
                        [941, 6],
                    ],
                },
                ComplexOutput: {
                    section: 'Outputs',
                    logicalId: 'ComplexOutput',
                    numPositions: 978,
                    valid: 975,
                    numVerifiedPositions: 978,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [942, 0],
                        [994, 5],
                        [994, 6],
                    ],
                },
                ConditionalOutput: {
                    section: 'Outputs',
                    logicalId: 'ConditionalOutput',
                    numPositions: 424,
                    valid: 421,
                    numVerifiedPositions: 424,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [995, 0],
                        [1019, 5],
                        [1019, 6],
                    ],
                },
                NestedFunctionOutput: {
                    section: 'Outputs',
                    logicalId: 'NestedFunctionOutput',
                    numPositions: 708,
                    valid: 706,
                    numVerifiedPositions: 708,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [1020, 0],
                        [1061, 5],
                    ],
                },
            },
        },
        yaml: {
            Metadata: {
                'AWS::CloudFormation::Interface': {
                    section: 'Metadata',
                    logicalId: 'AWS::CloudFormation::Interface',
                    numPositions: 172,
                    valid: 172,
                    numVerifiedPositions: 172,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                CustomMetadata: {
                    section: 'Metadata',
                    logicalId: 'CustomMetadata',
                    numPositions: 117,
                    valid: 117,
                    numVerifiedPositions: 117,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Parameters: {
                EnvironmentName: {
                    section: 'Parameters',
                    logicalId: 'EnvironmentName',
                    numPositions: 139,
                    valid: 139,
                    numVerifiedPositions: 139,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                VpcCidr: {
                    section: 'Parameters',
                    logicalId: 'VpcCidr',
                    numPositions: 184,
                    valid: 184,
                    numVerifiedPositions: 184,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                SubnetCidrs: {
                    section: 'Parameters',
                    logicalId: 'SubnetCidrs',
                    numPositions: 67,
                    valid: 67,
                    numVerifiedPositions: 67,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                DatabasePassword: {
                    section: 'Parameters',
                    logicalId: 'DatabasePassword',
                    numPositions: 68,
                    valid: 68,
                    numVerifiedPositions: 68,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                InstanceCount: {
                    section: 'Parameters',
                    logicalId: 'InstanceCount',
                    numPositions: 62,
                    valid: 62,
                    numVerifiedPositions: 62,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                AvailabilityZones: {
                    section: 'Parameters',
                    logicalId: 'AvailabilityZones',
                    numPositions: 75,
                    valid: 75,
                    numVerifiedPositions: 75,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                SSMParameter: {
                    section: 'Parameters',
                    logicalId: 'SSMParameter',
                    numPositions: 82,
                    valid: 82,
                    numVerifiedPositions: 82,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                BooleanParameter: {
                    section: 'Parameters',
                    logicalId: 'BooleanParameter',
                    numPositions: 69,
                    valid: 69,
                    numVerifiedPositions: 69,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Mappings: {
                RegionMap: {
                    section: 'Mappings',
                    logicalId: 'RegionMap',
                    numPositions: 131,
                    valid: 131,
                    numVerifiedPositions: 131,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                EnvironmentMap: {
                    section: 'Mappings',
                    logicalId: 'EnvironmentMap',
                    numPositions: 122,
                    valid: 122,
                    numVerifiedPositions: 122,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Conditions: {
                IsProduction: {
                    section: 'Conditions',
                    logicalId: 'IsProduction',
                    numPositions: 44,
                    valid: 44,
                    numVerifiedPositions: 44,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                IsNotProduction: {
                    section: 'Conditions',
                    logicalId: 'IsNotProduction',
                    numPositions: 32,
                    valid: 32,
                    numVerifiedPositions: 32,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                IsDevelopment: {
                    section: 'Conditions',
                    logicalId: 'IsDevelopment',
                    numPositions: 44,
                    valid: 44,
                    numVerifiedPositions: 44,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                IsProductionOrStaging: {
                    section: 'Conditions',
                    logicalId: 'IsProductionOrStaging',
                    numPositions: 76,
                    valid: 76,
                    numVerifiedPositions: 76,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                ComplexCondition: {
                    section: 'Conditions',
                    logicalId: 'ComplexCondition',
                    numPositions: 111,
                    valid: 111,
                    numVerifiedPositions: 111,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                HasMultipleAZs: {
                    section: 'Conditions',
                    logicalId: 'HasMultipleAZs',
                    numPositions: 58,
                    valid: 58,
                    numVerifiedPositions: 58,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Rules: {
                ValidateRegionAndEnvironment: {
                    section: 'Rules',
                    logicalId: 'ValidateRegionAndEnvironment',
                    numPositions: 370,
                    valid: 370,
                    numVerifiedPositions: 370,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                ValidateParameterCombinations: {
                    section: 'Rules',
                    logicalId: 'ValidateParameterCombinations',
                    numPositions: 492,
                    valid: 492,
                    numVerifiedPositions: 492,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Resources: {
                VPC: {
                    section: 'Resources',
                    logicalId: 'VPC',
                    numPositions: 265,
                    valid: 265,
                    numVerifiedPositions: 265,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                PublicSubnet: {
                    section: 'Resources',
                    logicalId: 'PublicSubnet',
                    numPositions: 367,
                    valid: 367,
                    numVerifiedPositions: 367,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                WebSecurityGroup: {
                    section: 'Resources',
                    logicalId: 'WebSecurityGroup',
                    numPositions: 552,
                    valid: 552,
                    numVerifiedPositions: 552,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                BastionSecurityGroup: {
                    section: 'Resources',
                    logicalId: 'BastionSecurityGroup',
                    numPositions: 194,
                    valid: 194,
                    numVerifiedPositions: 194,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                LaunchTemplate: {
                    section: 'Resources',
                    logicalId: 'LaunchTemplate',
                    numPositions: 470,
                    valid: 470,
                    numVerifiedPositions: 470,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                AutoScalingGroup: {
                    section: 'Resources',
                    logicalId: 'AutoScalingGroup',
                    numPositions: 628,
                    valid: 628,
                    numVerifiedPositions: 628,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                Database: {
                    section: 'Resources',
                    logicalId: 'Database',
                    numPositions: 637,
                    valid: 637,
                    numVerifiedPositions: 637,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                DatabaseSecurityGroup: {
                    section: 'Resources',
                    logicalId: 'DatabaseSecurityGroup',
                    numPositions: 207,
                    valid: 207,
                    numVerifiedPositions: 207,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                LambdaFunction: {
                    section: 'Resources',
                    logicalId: 'LambdaFunction',
                    numPositions: 778,
                    valid: 778,
                    numVerifiedPositions: 778,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                LambdaRole: {
                    section: 'Resources',
                    logicalId: 'LambdaRole',
                    numPositions: 607,
                    valid: 607,
                    numVerifiedPositions: 607,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                DatabaseAlarm: {
                    section: 'Resources',
                    logicalId: 'DatabaseAlarm',
                    numPositions: 395,
                    valid: 395,
                    numVerifiedPositions: 395,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                SNSTopic: {
                    section: 'Resources',
                    logicalId: 'SNSTopic',
                    numPositions: 255,
                    valid: 255,
                    numVerifiedPositions: 255,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Outputs: {
                VPCId: {
                    section: 'Outputs',
                    logicalId: 'VPCId',
                    numPositions: 93,
                    valid: 93,
                    numVerifiedPositions: 93,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                VPCCidr: {
                    section: 'Outputs',
                    logicalId: 'VPCCidr',
                    numPositions: 106,
                    valid: 106,
                    numVerifiedPositions: 106,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                DatabaseEndpoint: {
                    section: 'Outputs',
                    logicalId: 'DatabaseEndpoint',
                    numPositions: 146,
                    valid: 146,
                    numVerifiedPositions: 146,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                ComplexOutput: {
                    section: 'Outputs',
                    logicalId: 'ComplexOutput',
                    numPositions: 501,
                    valid: 501,
                    numVerifiedPositions: 501,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                ConditionalOutput: {
                    section: 'Outputs',
                    logicalId: 'ConditionalOutput',
                    numPositions: 234,
                    valid: 234,
                    numVerifiedPositions: 234,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                NestedFunctionOutput: {
                    section: 'Outputs',
                    logicalId: 'NestedFunctionOutput',
                    numPositions: 265,
                    valid: 265,
                    numVerifiedPositions: 265,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
        },
    },
    sample: {
        json: {
            Parameters: {
                StringParam: {
                    section: 'Parameters',
                    logicalId: 'StringParam',
                    numPositions: 286,
                    valid: 283,
                    numVerifiedPositions: 286,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [4, 0],
                        [17, 5],
                        [17, 6],
                    ],
                },
                NumberParam: {
                    section: 'Parameters',
                    logicalId: 'NumberParam',
                    numPositions: 91,
                    valid: 89,
                    numVerifiedPositions: 91,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [18, 0],
                        [18, 18],
                    ],
                },
                EnvironmentType: {
                    section: 'Parameters',
                    logicalId: 'EnvironmentType',
                    numPositions: 193,
                    valid: 190,
                    numVerifiedPositions: 193,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [24, 0],
                        [34, 5],
                        [34, 6],
                    ],
                },
                InstanceType: {
                    section: 'Parameters',
                    logicalId: 'InstanceType',
                    numPositions: 209,
                    valid: 207,
                    numVerifiedPositions: 209,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [35, 0],
                        [45, 5],
                    ],
                },
            },
            Mappings: {
                EnvironmentMap: {
                    section: 'Mappings',
                    logicalId: 'EnvironmentMap',
                    numPositions: 245,
                    valid: 242,
                    numVerifiedPositions: 245,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 3,
                    entityMismatchErrors: 3,
                    failingPositions: [
                        [48, 0],
                        [64, 5],
                        [64, 6],
                    ],
                },
                RegionMap: {
                    section: 'Mappings',
                    logicalId: 'RegionMap',
                    numPositions: 117,
                    valid: 115,
                    numVerifiedPositions: 117,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [65, 0],
                        [65, 16],
                    ],
                },
            },
            Conditions: {
                IsProd: {
                    section: 'Conditions',
                    logicalId: 'IsProd',
                    numPositions: 83,
                    valid: 81,
                    numVerifiedPositions: 83,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [75, 0],
                        [75, 13],
                    ],
                },
                IsTest: {
                    section: 'Conditions',
                    logicalId: 'IsTest',
                    numPositions: 83,
                    valid: 81,
                    numVerifiedPositions: 83,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [83, 0],
                        [83, 13],
                    ],
                },
                IsDev: {
                    section: 'Conditions',
                    logicalId: 'IsDev',
                    numPositions: 81,
                    valid: 79,
                    numVerifiedPositions: 81,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [91, 0],
                        [91, 12],
                    ],
                },
                CreateProdResources: {
                    section: 'Conditions',
                    logicalId: 'CreateProdResources',
                    numPositions: 44,
                    valid: 42,
                    numVerifiedPositions: 44,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [99, 0],
                        [99, 26],
                    ],
                },
            },
            Resources: {
                MyS3Bucket: {
                    section: 'Resources',
                    logicalId: 'MyS3Bucket',
                    numPositions: 110,
                    valid: 108,
                    numVerifiedPositions: 110,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [104, 0],
                        [104, 17],
                    ],
                },
                MyEC2Instance: {
                    section: 'Resources',
                    logicalId: 'MyEC2Instance',
                    numPositions: 327,
                    valid: 326,
                    numVerifiedPositions: 327,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[112, 0]],
                },
                ProdOnlyS3Bucket: {
                    section: 'Resources',
                    logicalId: 'ProdOnlyS3Bucket',
                    numPositions: 249,
                    valid: 248,
                    numVerifiedPositions: 249,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[135, 0]],
                },
                ComprehensiveResource: {
                    section: 'Resources',
                    logicalId: 'ComprehensiveResource',
                    numPositions: 583,
                    valid: 582,
                    numVerifiedPositions: 583,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[152, 0]],
                },
                ExampleLambdaFunction: {
                    section: 'Resources',
                    logicalId: 'ExampleLambdaFunction',
                    numPositions: 736,
                    valid: 735,
                    numVerifiedPositions: 736,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[188, 0]],
                },
                LambdaExecutionRole: {
                    section: 'Resources',
                    logicalId: 'LambdaExecutionRole',
                    numPositions: 359,
                    valid: 358,
                    numVerifiedPositions: 359,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 1,
                    entityMismatchErrors: 1,
                    failingPositions: [[237, 0]],
                },
            },
            Outputs: {
                BucketName: {
                    section: 'Outputs',
                    logicalId: 'BucketName',
                    numPositions: 94,
                    valid: 90,
                    numVerifiedPositions: 94,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 4,
                    entityMismatchErrors: 4,
                    failingPositions: [
                        [259, 0],
                        [259, 2],
                        [259, 3],
                        [259, 17],
                    ],
                },
            },
        },
        yaml: {
            Parameters: {
                StringParam: {
                    section: 'Parameters',
                    logicalId: 'StringParam',
                    numPositions: 229,
                    valid: 229,
                    numVerifiedPositions: 229,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                NumberParam: {
                    section: 'Parameters',
                    logicalId: 'NumberParam',
                    numPositions: 64,
                    valid: 64,
                    numVerifiedPositions: 64,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                EnvironmentType: {
                    section: 'Parameters',
                    logicalId: 'EnvironmentType',
                    numPositions: 152,
                    valid: 152,
                    numVerifiedPositions: 152,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                InstanceType: {
                    section: 'Parameters',
                    logicalId: 'InstanceType',
                    numPositions: 175,
                    valid: 175,
                    numVerifiedPositions: 175,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Mappings: {
                EnvironmentMap: {
                    section: 'Mappings',
                    logicalId: 'EnvironmentMap',
                    numPositions: 184,
                    valid: 184,
                    numVerifiedPositions: 184,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                RegionMap: {
                    section: 'Mappings',
                    logicalId: 'RegionMap',
                    numPositions: 87,
                    valid: 87,
                    numVerifiedPositions: 87,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Conditions: {
                IsProd: {
                    section: 'Conditions',
                    logicalId: 'IsProd',
                    numPositions: 38,
                    valid: 38,
                    numVerifiedPositions: 38,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                IsTest: {
                    section: 'Conditions',
                    logicalId: 'IsTest',
                    numPositions: 38,
                    valid: 36,
                    numVerifiedPositions: 38,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [64, 0],
                        [64, 1],
                    ],
                },
                IsDev: {
                    section: 'Conditions',
                    logicalId: 'IsDev',
                    numPositions: 37,
                    valid: 35,
                    numVerifiedPositions: 37,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [65, 0],
                        [65, 1],
                    ],
                },
                CreateProdResources: {
                    section: 'Conditions',
                    logicalId: 'CreateProdResources',
                    numPositions: 26,
                    valid: 24,
                    numVerifiedPositions: 26,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [66, 0],
                        [66, 1],
                    ],
                },
            },
            Resources: {
                MyS3Bucket: {
                    section: 'Resources',
                    logicalId: 'MyS3Bucket',
                    numPositions: 69,
                    valid: 69,
                    numVerifiedPositions: 69,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                MyEC2Instance: {
                    section: 'Resources',
                    logicalId: 'MyEC2Instance',
                    numPositions: 155,
                    valid: 155,
                    numVerifiedPositions: 155,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                ProdOnlyS3Bucket: {
                    section: 'Resources',
                    logicalId: 'ProdOnlyS3Bucket',
                    numPositions: 149,
                    valid: 149,
                    numVerifiedPositions: 149,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                ComprehensiveResource: {
                    section: 'Resources',
                    logicalId: 'ComprehensiveResource',
                    numPositions: 418,
                    valid: 418,
                    numVerifiedPositions: 418,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
                ExampleLambdaFunction: {
                    section: 'Resources',
                    logicalId: 'ExampleLambdaFunction',
                    numPositions: 597,
                    valid: 593,
                    numVerifiedPositions: 597,
                    noContext: 0,
                    topLevelErrors: 4,
                    logicalIdErrors: 4,
                    entityMismatchErrors: 4,
                    failingPositions: [
                        [119, 0],
                        [125, 0],
                        [131, 0],
                        [140, 0],
                    ],
                },
                LambdaExecutionRole: {
                    section: 'Resources',
                    logicalId: 'LambdaExecutionRole',
                    numPositions: 261,
                    valid: 261,
                    numVerifiedPositions: 261,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
            Outputs: {
                BucketName: {
                    section: 'Outputs',
                    logicalId: 'BucketName',
                    numPositions: 63,
                    valid: 63,
                    numVerifiedPositions: 63,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 0,
                    entityMismatchErrors: 0,
                    failingPositions: [],
                },
            },
        },
    },
    simple: {
        json: {
            Resources: {
                MyS3Bucket: {
                    section: 'Resources',
                    logicalId: 'MyS3Bucket',
                    numPositions: 46,
                    valid: 42,
                    numVerifiedPositions: 46,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 4,
                    entityMismatchErrors: 4,
                    failingPositions: [
                        [3, 0],
                        [3, 2],
                        [3, 3],
                        [3, 17],
                    ],
                },
            },
        },
        yaml: {
            Resources: {
                MyS3Bucket: {
                    section: 'Resources',
                    logicalId: 'MyS3Bucket',
                    numPositions: 33,
                    valid: 31,
                    numVerifiedPositions: 33,
                    noContext: 0,
                    topLevelErrors: 0,
                    logicalIdErrors: 2,
                    entityMismatchErrors: 2,
                    failingPositions: [
                        [2, 0],
                        [2, 1],
                    ],
                },
            },
        },
    },
};
