AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::LanguageExtensions

Constants:
  foo: bar
  sub: "${Const::foo}-abc-${AWS::AccountId}"
  obj:
    TestObject:
      A: b

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      Test: !Sub ${Const::sub}-xyz
      TestObj: !Ref Const::obj
    Properties:
      BucketName: !Sub ${Const::foo}
  
  PersonalS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-personal-bucket
